# Generated by Django 5.0.4 on 2024-05-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled_2fa',
            field=models.BooleanField(default=False),
        ),
    ]
