# Generated by Django 5.0.4 on 2024-04-24 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='user.Friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
