# Generated by Django 5.0.4 on 2024-04-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_friends'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('requster', 'addressee'), name='unique_requster_addressee'),
        ),
    ]
