# Generated by Django 5.0.4 on 2024-04-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_friends_unique_requster_addressee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.CheckConstraint(check=models.Q(('requster', models.F('addressee')), _negated=True), name='requster_and_addressee_must_be_different'),
        ),
    ]
