# Generated by Django 5.0.4 on 2024-04-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_friends_requster_and_addressee_must_be_different'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
