# Generated by Django 5.0.4 on 2024-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_friends_is_blocked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achivments',
            name='requirment',
        ),
        migrations.AddField(
            model_name='achivments',
            name='requirement_type',
            field=models.CharField(default='join', max_length=200),
        ),
        migrations.AddField(
            model_name='achivments',
            name='requirement_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achivments',
            name='reward_coins',
            field=models.IntegerField(default=100),
        ),
        migrations.DeleteModel(
            name='AchivmentsRequirment',
        ),
    ]
