# Generated by Django 5.0.4 on 2024-04-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_ranks_achivments_updated_at_friends_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankinglogs',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankinglogs', to='user.ranks'),
        ),
    ]
