# Generated by Django 5.0.4 on 2024-04-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_rankinglogs_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ranking_logs',
            field=models.ManyToManyField(through='user.RankingLogs', to='user.ranks'),
        ),
    ]
