# Generated by Django 5.0.4 on 2024-04-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
